### ISSUE TITLE
Content-based-chunking

### ISSUE THREAD

**Issue by phiresky** [RangerMauve/js-ipfs-unixfs-offset-chunker#3]
I just wanted to mention this, in case you did not know about it and in case it is relevant (not sure what this project does), that it's possible to do chunking of a stream of data at deterministic boundaries based on the content in order to improve the deduplication to better levels than doing fixed-size chunking. (especially if the stream of data consists of multiple smaller things that are common between multiple streams but may be concatenated in different ways)

Called Rabin fingerprinting / content-based-chunking, see https://blog.gopheracademy.com/advent-2018/split-data-with-cdc/

Please forgive me if this is not relevant to this project

**Comment by RangerMauve** [comment]
Thank you for the links! This library is primarily made to be used in cases where you know the offsets for chunks ahead of time such as zip files where you have some metadata available ahead of time.

I think rabin fingerprinting is going to be left to libraries building on top of this, or using some fancier approaches for their actual chunker. 😁
